openapi: "3.1.0"
info:
  title: "property_service API"
  description: "DeRent5 Property Management API"
  version: "1.0.0"
servers:
  - url: "https://property_service"
paths:
  /api/v1/properties:
    post:
      summary: "Create new property listing"
      operationId: "createProperty"
      parameters:
        - name: "X-User-Id"
          in: "header"
          required: true
          schema:
            type: "string"
        - name: "X-User-Roles"
          in: "header"
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: "object"
              required:
                - "input"
                - "images"
              properties:
                input:
                  $ref: "#/components/schemas/CreatePropertyRequest"
                images:
                  type: "array"
                  items:
                    type: "string"
                    format: "binary"
  /api/v1/properties/{id}:
    put:
      summary: "Update property details"
      operationId: "updateProperty"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "X-User-Id"
          in: "header"
          required: true
          schema:
            type: "string"
        - name: "X-User-Roles"
          in: "header"
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePropertyRequest"
    delete:
      summary: "Delete property"
      operationId: "deleteProperty"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "X-User-Id"
          in: "header"
          required: true
          schema:
            type: "string"
        - name: "X-User-Roles"
          in: "header"
          required: true
          schema:
            type: "string"
  /api/v1/properties/{id}/approve:
    patch:
      summary: "Approve property (ADMIN only)"
      operationId: "approveProperty"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "X-User-Id"
          in: "header"
          required: true
          schema:
            type: "string"
        - name: "X-User-Roles"
          in: "header"
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApprovePropertyRequest"
components:
  schemas:
    Property:
      type: "object"
      properties:
        id:
          type: "string"
        userId:
          type: "string"
        status:
          type: "string"
          enum:
            - "DRAFT"
            - "PENDING_APPROVAL"
            - "APPROVED"
            - "SUSPENDED"
            - "HIDDEN"
            - "ARCHIVED"
        price:
          type: "number"
          format: "double"
        capacity:
          type: "integer"
        title:
          type: "string"
        description:
          type: "string"
    CreatePropertyRequest:
      type: "object"
      properties:
        title:
          type: "string"
        description:
          type: "string"
        typeId:
          type: "integer"
        price:
          type: "number"
        capacity:
          type: "integer"
